# fly.toml app configuration file generated for armanybase on 2023-09-11T15:47:26-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "armanybase"
primary_region = "lax"

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
